### ISSUE TITLE
[Bug] View [auth.login.] not found.

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/theme-coreuiv4#7]
# Bug report

### What I did

Changed theme to CoreUIv4.

### What I expected to happen

Auth views to work.

### What happened

Login view doesn't work:
<img width="1512" alt="CleanShot 2023-05-04 at 10 40 00@2x" src="https://user-images.githubusercontent.com/1032474/236153772-14ddc95b-5032-4bba-bc80-70f924ad5e56.png">

**Comment by tabacitu** [comment]
@maurohmartinez I see the same thing is happening in CoreUIv2 - https://github.com/Laravel-Backpack/theme-coreuiv2/issues/5

This is fishy. Why is it only working in Tabler? This was working before right... so have we pushed a breaking change in CRUD to make smth work in Tabler? Something that broke CoreUI v2 and v4? What's happening here?

**Comment by maurohmartinez** [comment]
Hmm, this is weird. I am testing and it works when switching themes.
I am using:

- demo `v6`
- crud `v6`
- theme-tabler `main`
- coreui2 `main`
- coreui4 `main`

Are you using those same branches?

Tabler does have a different folder structure for login/register blade files, but those are included only by the theme itself, not other themes, nor CRUD. AFAIK 🤔

**Comment by tabacitu** [comment]
Installed a new Demo. Ran everything again. Could not replicate 🤦‍♂️ Don't know what that was...

**Comment by gitderekz** [comment]
In my case i had this error, **Could not find Backpack view [backpack.ui::auth.login**
I solved by going to file  **vendor\backpack\crud\src\helpers.php**
and changed the line **config('backpack.ui.view_namespace')** to **config('backpack.ui:view_namespace').$view,**
**NOTE** difference between **ui.view** and **ui:view**

**Comment by pxpm** [comment]
Hello @gitderekz thanks for the heads up 🙏 

Please don't comment on closed issues, we still get the notifications, but we don't mind having a different issue for a similar problem as long as it adds something new to the issue, like what you have mentioned. This seems that you could have opened a new issue, mentioned this one if you feel it has some links and we will treat your specific use case. 

From this issue history it seems that @tabacitu was getting this issue and after update he got no issues, so I would assume you need to update your package versions too. 

I will open an exception here, can you please provide me some additional information ? 

Can you tell me what bp package versions are you using with: `php artisan backpack:version` ? also, can you post your `config/backpack/ui.php` file ?

Cheers
